/**
 * Tests for StudentTable component routing
 * Catches the exact issue where View Report links were broken
 */
import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/svelte'
import StudentTable from '../components/StudentTable.svelte'
import type { Student } from '../lib/data'

const mockStudents: Student[] = [
  {
    student_dcid: '42318',
    student_number: 2034095,
    first_name: 'Fizz',
    last_name: 'Tester',
    grade_level: 4,
    home_room: '15',
    response: {
      id: '123',
      submitted_at: '2024-01-01T00:00:00Z',
      fields: []
    }
  },
  {
    student_dcid: '42319',
    student_number: 2034096,
    first_name: 'Buzz',
    last_name: 'Tester',
    grade_level: 5,
    home_room: '16',
    response: {
      id: '124',
      submitted_at: '2024-01-01T00:00:00Z',
      fields: []
    }
  }
]

describe('StudentTable Component', () => {
  it('should render student data correctly', () => {
    render(StudentTable, { students: mockStudents })
    
    expect(screen.getByText('Fizz Tester')).toBeInTheDocument()
    expect(screen.getByText('Buzz Tester')).toBeInTheDocument()
    expect(screen.getByText('2034095')).toBeInTheDocument()
    expect(screen.getByText('Grade 4')).toBeInTheDocument()
  })

  it('should generate correct View Report links using linkHelpers', () => {
    render(StudentTable, { students: mockStudents })
    
    // Find all "View Report" links
    const reportLinks = screen.getAllByText('View Report')
    expect(reportLinks).toHaveLength(2)
    
    // Check that the first link has the correct href
    const firstLink = reportLinks[0].closest('a')
    expect(firstLink).toHaveAttribute('href', '/eld-progress-report/report.html?student_dcid=42318')
    
    // Check that the second link has the correct href
    const secondLink = reportLinks[1].closest('a')
    expect(secondLink).toHaveAttribute('href', '/eld-progress-report/report.html?student_dcid=42319')
  })

  it('should NEVER generate hardcoded /src/ paths', () => {
    render(StudentTable, { students: mockStudents })
    
    // Get all links in the table
    const allLinks = screen.getAllByRole('link')
    
    allLinks.forEach(link => {
      const href = link.getAttribute('href') || ''
      
      // These patterns should NEVER appear in our links
      expect(href).not.toContain('/src/powerschool/WEB_ROOT')
      expect(href).not.toMatch(/^\/src\//)
      
      // All report links should use BASE_URL
      if (href.includes('report.html')) {
        expect(href).toMatch(/^\/eld-progress-report\//)
      }
    })
  })

  it('should use linkHelpers consistently across portals', () => {
    // Test admin portal
    const { rerender } = render(StudentTable, { 
      students: mockStudents, 
      portal: 'admin' 
    })
    
    let reportLink = screen.getAllByText('View Report')[0].closest('a')
    expect(reportLink).toHaveAttribute('href', '/eld-progress-report/report.html?student_dcid=42318')
    
    // Test teachers portal - should generate same URL since linkHelpers handles context
    rerender({ students: mockStudents, portal: 'teachers' })
    
    reportLink = screen.getAllByText('View Report')[0].closest('a')
    expect(reportLink).toHaveAttribute('href', '/eld-progress-report/report.html?student_dcid=42318')
    
    // Test guardian portal
    rerender({ students: mockStudents, portal: 'guardian' })
    
    reportLink = screen.getAllByText('View Report')[0].closest('a')
    expect(reportLink).toHaveAttribute('href', '/eld-progress-report/report.html?student_dcid=42318')
  })

  it('should handle missing student data gracefully', () => {
    render(StudentTable, { students: [] })
    
    // Should not crash and should show no students
    expect(screen.queryByText('View Report')).not.toBeInTheDocument()
  })
})

/**
 * Integration test to verify the exact fix we applied
 */
describe('StudentTable - Regression Test for BASE_URL Issue', () => {
  it('should use reportUrl from linkHelpers, not manual URL construction', () => {
    render(StudentTable, { students: mockStudents })
    
    const reportLinks = screen.getAllByText('View Report')
    
    reportLinks.forEach((linkElement, index) => {
      const link = linkElement.closest('a')
      const href = link?.getAttribute('href')
      
      // Verify it follows the pattern generated by reportUrl()
      const expectedHref = `/eld-progress-report/report.html?student_dcid=${mockStudents[index].student_dcid}`
      expect(href).toBe(expectedHref)
      
      // Verify it DOES NOT follow the old broken pattern
      const brokenPattern = `/src/powerschool/WEB_ROOT/admin/eld-progress-report/report.html?student_dcid=${mockStudents[index].student_dcid}`
      expect(href).not.toBe(brokenPattern)
    })
  })
})