#!/bin/bash

# File Survey Script - Analyzes codebase files and generates FILE_SURVEY.md
# Usage: ./file-survey.sh [directory] [file_patterns...]
# Example: ./file-survey.sh src "*.svelte" "*.ts" "*.js" "*.html"

set -e

# Default values
SURVEY_DIR="${1:-src}"
OUTPUT_FILE="FILE_SURVEY.md"
TEMP_DIR=$(mktemp -d)

# Default file patterns if none provided
if [ $# -lt 2 ]; then
    FILE_PATTERNS=("*.svelte" "*.html" "*.js" "*.ts" "*.jsx" "*.tsx" "*.vue" "*.css" "*.scss")
else
    shift # Remove directory argument
    FILE_PATTERNS=("$@")
fi

echo "🔍 Starting file survey of: $SURVEY_DIR"
echo "📁 Patterns: ${FILE_PATTERNS[*]}"
echo "📄 Output: $OUTPUT_FILE"

# Initialize output file
{
    echo "# File Survey Report"
    echo ""
    echo "> Auto-generated file analysis and descriptions"
    echo ""
    echo "## Overview"
    echo ""
    echo "This document provides a comprehensive overview of all analyzed files in the codebase, with AI-generated descriptions of purpose, functionality, and key features."
    echo ""
    echo "**Generated:** $(date)"
    echo "**Directory:** $SURVEY_DIR"
    echo "**Patterns:** ${FILE_PATTERNS[*]}"
    echo ""
    echo "---"
    echo ""
} > "$OUTPUT_FILE"

# Function to analyze a single file
analyze_file() {
    local file_path="$1"
    local relative_path="${file_path#./}"
    local temp_output="$TEMP_DIR/$(basename "$file_path").analysis"
    
    echo "📝 Analyzing: $relative_path"
    
    # Create Hermes prompt for file analysis
    cat > "$temp_output.prompt" << EOF
Analyze this file and provide a brief, focused description (2-3 sentences max).

Focus on:
- Primary purpose/functionality  
- Key components or exports
- Role in the application

File: $relative_path
Content:
---
$(cat "$file_path")
---

Respond with ONLY the description text, no markdown formatting, no file path repetition.
EOF

    # Run Hermes analysis (capture output, handle errors gracefully)
    if hermes chat -q "$(cat "$temp_output.prompt")" --quiet > "$temp_output.result" 2>/dev/null; then
        # Success - add to survey file (with atomic write to prevent corruption)
        local temp_entry="$TEMP_DIR/entry_$(basename "$file_path")_$$"
        {
            echo "### \`$relative_path\`"
            echo
            cat "$temp_output.result"
            echo
            echo "---"
            echo
        } > "$temp_entry"
        
        # Atomic append using lockfile approach
        (
            local lockfile="$OUTPUT_FILE.lock"
            while ! (set -C; echo $$ > "$lockfile") 2>/dev/null; do
                sleep 0.1
            done
            cat "$temp_entry" >> "$OUTPUT_FILE"
            rm "$lockfile"
        )
        echo "✅ Complete: $relative_path"
    else
        # Error - add placeholder
        {
            echo "### \`$relative_path\`"
            echo
            echo "*Analysis failed - manual review needed*"
            echo
            echo "---"
            echo
        } >> "$OUTPUT_FILE"
        echo "❌ Failed: $relative_path"
    fi
}

# Find and analyze files
echo "🔍 Finding files..."

total_files=0
for pattern in "${FILE_PATTERNS[@]}"; do
    while IFS= read -r -d '' file; do
        if [ -f "$file" ] && [ -s "$file" ]; then  # File exists and is not empty
            analyze_file "$file"  # Run sequentially, not in background
            ((total_files++))
        fi
    done < <(find "$SURVEY_DIR" -name "$pattern" -type f -print0 2>/dev/null)
done

# Add footer
cat >> "$OUTPUT_FILE" << EOF
## Summary

**Total Files Analyzed:** $total_files files
**Generated:** $(date)

---

*This survey was auto-generated by file-survey.sh. For manual updates, edit individual file descriptions above.*
EOF

# Cleanup
rm -rf "$TEMP_DIR"

echo
echo "✅ Survey complete!"
echo "📄 Results written to: $OUTPUT_FILE"
echo "📊 Total files analyzed: $total_files"
echo
echo "📖 View results:"
echo "   cat $OUTPUT_FILE"
echo "   code $OUTPUT_FILE"